"""Self-contained HTML dashboard renderer (inline CSS/JS, no external assets)."""
import json
import time


def _safe_json(obj):
    # Prevent a literal </script> from breaking out of the inline <script>.
    return json.dumps(obj).replace("</", "<\\/")


def build_dashboard(cves, news, stats):
    generated = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    data = {
        "cves": [{
            "cve": c.get("cve_id"),
            "score": c.get("score") or 0,
            "tier": c.get("tier") or "-",
            "cvss": c.get("cvss"),
            "epss": c.get("epss"),
            "kev": bool(c.get("in_kev")),
            "desc": (c.get("description") or "")[:240],
            "ref": (c.get("refs") or "").split(" ")[0] if c.get("refs") else "",
        } for c in cves],
        "news": [{
            "title": n.get("title") or "",
            "link": n.get("link") or "",
            "source": n.get("source") or "",
            "published": n.get("published") or "",
        } for n in news],
        "stats": stats,
        "generated": generated,
    }
    return _TEMPLATE.replace("__DATA__", _safe_json(data))


_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>ThreatScope Dashboard</title>
<style>
:root{--bg:#0b1020;--card:#141b2e;--ink:#e6ebf5;--mut:#8a97b1;--line:#26314d}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 -apple-system,Segoe UI,Roboto,Arial,sans-serif}
header{padding:18px 24px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px}
h1{margin:0;font-size:20px;letter-spacing:.5px}
h1 b{color:#5b8cff}
h2{font-size:15px;margin:24px 0 8px}
.muted{color:var(--mut);font-size:12px}
.wrap{padding:20px 24px;max-width:1200px;margin:0 auto}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:8px}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px 16px}
.card .n{font-size:26px;font-weight:700}
.card .l{color:var(--mut);font-size:12px;text-transform:uppercase;letter-spacing:.5px}
.controls{display:flex;gap:10px;margin:10px 0;flex-wrap:wrap;align-items:center}
input,select{background:var(--card);border:1px solid var(--line);color:var(--ink);border-radius:8px;padding:8px 10px;font-size:13px}
table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden}
th,td{padding:9px 12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}
th{font-size:12px;text-transform:uppercase;letter-spacing:.4px;color:var(--mut);cursor:pointer;user-select:none;white-space:nowrap}
tr:hover td{background:#1a2238}
.score{font-weight:700}
.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:11px;font-weight:700}
.Critical{background:rgba(239,68,68,.16);color:#fca5a5}
.High{background:rgba(245,158,11,.16);color:#fcd34d}
.Medium{background:rgba(59,130,246,.16);color:#93c5fd}
.Low{background:rgba(100,116,139,.20);color:#cbd5e1}
.kevyes{color:#fca5a5;font-weight:700}
a{color:#7aa2ff;text-decoration:none}
a:hover{text-decoration:underline}
.cve{font-family:ui-monospace,Consolas,monospace;white-space:nowrap}
.desc{color:#cdd6ea;max-width:520px}
ul.news{list-style:none;padding:0;margin:0}
ul.news li{padding:8px 0;border-bottom:1px solid var(--line)}
ul.news .src{color:var(--mut);font-size:12px;margin-right:8px}
footer{padding:18px 24px;color:var(--mut);font-size:12px;border-top:1px solid var(--line);text-align:center}
</style>
</head>
<body>
<header>
  <h1>Threat<b>Scope</b></h1>
  <div class="muted" id="gen"></div>
</header>
<div class="wrap">
  <div class="cards" id="cards"></div>

  <h2>Prioritized vulnerabilities</h2>
  <div class="controls">
    <input id="q" placeholder="Filter CVE or keyword..." oninput="renderTable()" style="flex:1;min-width:200px"/>
    <select id="tier" onchange="renderTable()">
      <option value="">All tiers</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option>
    </select>
    <label class="muted" style="display:flex;align-items:center;gap:6px"><input type="checkbox" id="kevonly" onchange="renderTable()"/> KEV only</label>
  </div>
  <table>
    <thead><tr>
      <th data-k="score">Score</th><th data-k="tier">Tier</th><th data-k="cve">CVE</th>
      <th data-k="cvss">CVSS</th><th data-k="epss">EPSS</th><th>KEV</th><th>Description</th>
    </tr></thead>
    <tbody id="rows"></tbody>
  </table>

  <h2>Latest security news</h2>
  <ul class="news" id="news"></ul>
</div>
<footer>Generated by ThreatScope &middot; public data only &middot; <span id="genf"></span></footer>

<script>
const DATA = __DATA__;
let sortKey="score", sortDir=-1;
const $=function(id){return document.getElementById(id)};
$("gen").textContent="Updated "+DATA.generated;
$("genf").textContent=DATA.generated;

function esc(s){return (s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}

function cards(){
  const s=DATA.stats||{};
  const d=[["Total CVEs",s.total_cves||0],["KEV (exploited)",s.kev||0],["Critical",s.critical||0],["News",s.news||0],["IOCs",s.iocs||0]];
  $("cards").innerHTML=d.map(x=>"<div class='card'><div class='n'>"+x[1]+"</div><div class='l'>"+x[0]+"</div></div>").join("");
}
function fmtEpss(v){return v==null?"-":(v*100).toFixed(1)+"%"}
function fmtCvss(v){return v==null?"-":Number(v).toFixed(1)}

function renderTable(){
  const q=($("q").value||"").toLowerCase(), tier=$("tier").value, kevonly=$("kevonly").checked;
  let rows=DATA.cves.filter(function(r){
    if(tier && r.tier!==tier) return false;
    if(kevonly && !r.kev) return false;
    if(q && !((r.cve||"").toLowerCase().includes(q) || (r.desc||"").toLowerCase().includes(q))) return false;
    return true;
  });
  rows.sort(function(a,b){
    let x=a[sortKey], y=b[sortKey];
    if(sortKey==="cve"||sortKey==="tier"){x=(""+x).toLowerCase();y=(""+y).toLowerCase();return x<y?-sortDir:x>y?sortDir:0;}
    x=(x==null?-1:x); y=(y==null?-1:y); return (x-y)*sortDir;
  });
  $("rows").innerHTML=rows.map(function(r){
    const cve=r.ref?("<a href='"+esc(r.ref)+"' target='_blank' rel='noopener'>"+esc(r.cve)+"</a>"):esc(r.cve);
    return "<tr><td class='score'>"+(r.score||0).toFixed(1)+"</td>"+
      "<td><span class='badge "+r.tier+"'>"+r.tier+"</span></td>"+
      "<td class='cve'>"+cve+"</td><td>"+fmtCvss(r.cvss)+"</td><td>"+fmtEpss(r.epss)+"</td>"+
      "<td>"+(r.kev?"<span class='kevyes'>YES</span>":"-")+"</td>"+
      "<td class='desc'>"+esc(r.desc)+"</td></tr>";
  }).join("") || "<tr><td colspan='7' class='muted' style='padding:18px'>No matching CVEs. Run an update first.</td></tr>";
}
function news(){
  $("news").innerHTML=DATA.news.map(function(n){
    const t=esc(n.title);
    const link=n.link?("<a href='"+esc(n.link)+"' target='_blank' rel='noopener'>"+t+"</a>"):t;
    return "<li><span class='src'>"+esc(n.source)+"</span>"+link+"</li>";
  }).join("") || "<li class='muted'>No news yet.</li>";
}
document.querySelectorAll("th[data-k]").forEach(function(th){
  th.addEventListener("click",function(){
    const k=th.getAttribute("data-k");
    if(sortKey===k) sortDir*=-1; else {sortKey=k; sortDir=(k==="cve"||k==="tier")?1:-1;}
    renderTable();
  });
});
cards(); news(); renderTable();
</script>
</body>
</html>
"""
